spring:
  application:
    name: TelegranLoader

telegram:
  common:
    downloadpath: /tmp
    owners:
      - 0
      - 1
    dry-run: true
  api:
    api_id: 0
    api_hash: 012345
    app_version: 1.0
    model: Model
    system_version: SysVer
    language_code: en
    phone_number: +000000000000
    database_path: /tmp
    tdlib_log: /tmp/tdlib.log
  bot:
    username: telegranLoaderBot
    token: 0123456:asbcdefghijkl
    chatid: 0123345

series:
  filename:
    parser:
      "[^[BO]+[0-9]+[_]?[A-Z]+[.][a-zA-Z0-9]+]":
        logical_name: boruto
        type: anime
        filename:
          fixed: Boruto
        season:
          fixed: 01
        episode:
          regexp: "[0-9]+"
      "[^Boku No Hero Academia [0-9]+Th Season - [0-9]{2}.[a-zA-Z0-9]+]":
        logical_name: Boku No Hero Academia
        type: anime
        filename:
          regexp: "[0-9]"
        season:
          regexp: "[0-9]"
        episode:
          regexp: "[0-9]{2}"
      "[.*[S][0-9]{2}[E][0-9]{2}.*]":
        logical_name: Generic Series
        type: TVSeries
        filename:
          regexp: "[S][0-9]{2}[E][0-9]{2}"
        season:
          regexp: "[S][0-9]{2}"
          replace: "S"
        episode:
          regexp: "[E][0-9]{2}"
          replace: "E"
  caption:
    parser:
      "[Phantom Blood - EP - [0-9]{1,3} - SUBITA .* @WatchAnime.*]":
        logical_name: JoJo Bizarre Adventure
        type: anime
        filename:
          fixed: JoJo Bizarre Adventure
        season:
          fixed: "1"
        episode:
          regexp: "[0-9]{1,3}"
      "[Battle Tendency - EP - [0-9]{1,3} - SUBITA .* @WatchAnime.*]":
        logical_name: JoJo Bizarre Adventure
        type: anime
        filename:
          fixed: JoJo Bizarre Adventure
        season:
          fixed: "2"
        episode:
          regexp: "[0-9]{1,3}"
      "[Stardust Crusaders - EP - [0-9]{1,3} - SUBITA .* @WatchAnime.*]":
        logical_name: JoJo Bizarre Adventure
        type: anime
        filename:
          fixed: JoJo Bizarre Adventure
        season:
          fixed: "3"
        episode:
          regexp: "[0-9]{1,3}"
      "[Diamond is Unbreakable - EP - [0-9]{1,3} - SUBITA .* @WatchAnime.*]":
        logical_name: JoJo Bizarre Adventure
        type: anime
        filename:
          fixed: JoJo Bizarre Adventure
        season:
          fixed: "4"
        episode:
          regexp: "[0-9]{1,3}"
      "[Vento Aureo - EP - [0-9]{1,3} - SUBITA .* @WatchAnime.*]":
        logical_name: JoJo Bizarre Adventure
        type: anime
        filename:
          fixed: JoJo Bizarre Adventure
        season:
          fixed: "5"
        episode:
          regexp: "[0-9]{1,3}"
logging:
  level:
    root: error
    it.usuratonkachi: info
